### ISSUE TITLE
Default user always created without password

### ISSUE THREAD

**Issue by t2d** [systemli/ansible-role-mariadb#2]
https://github.com/systemli/ansible-role-mariadb/blob/3e72306b4e7eb230380cc9b587a17ff66536af25/tasks/main.yml#L20

Is this task even necessary? Shouldn't we go with the code that is in `users.yml`?

**Comment by doobry-systemli** [comment]
I remember that this was necessary some time ago in order to get a default admin user who works with the credentials provided in `/root/.my.cf`. But this might have been fixed in the Debian package in the meantime.

You could try to disable the tasks `create MariaDB admin user` and `create MariaDB /root/.my.cnf` and see whether a simple `mysql` as user root still successfully authenticates to the local MariaDB server.
